-- 0063_client_journey.sql
-- What she actually did: one row per visit, one per action inside it, and the
-- DOM recording so the visit can be watched back. Requires 0029 (pilot_member).
-- Service-role only, like every pilot table: RLS on with zero policies.
-- Idempotent -- safe to run again if an earlier attempt got partway.
-- Kept deliberately short so it pastes into the SQL editor in one piece.

create table if not exists public.client_session (
  session_id    uuid primary key,
  member_id     uuid not null references public.pilot_member(member_id) on delete cascade,
  auth_user_id  uuid,
  started_at    timestamptz not null default now(),
  -- Duration is last_seen_at - started_at, the definition site_session (0013)
  -- uses, so the two dashboards cannot disagree about "time on app".
  last_seen_at  timestamptz not null default now(),
  -- Only the time the tab was actually in front of her: the tracker stops the
  -- clock when it is hidden, so a tab left open all day is not a long visit.
  active_ms     bigint not null default 0,
  entry_path    text,
  is_returning  boolean not null default false,
  device        text,
  viewport_w    int,
  viewport_h    int,
  user_agent    text,
  country       text,
  referrer      text,
  has_recording boolean not null default false,
  ended_at      timestamptz
);
create index if not exists idx_client_session_member on public.client_session (member_id, started_at desc);
create index if not exists idx_client_session_started on public.client_session (started_at desc);
alter table public.client_session enable row level security;

-- event_id is an identity column rather than a uuid: this is the one table
-- whose insertion order matters, because the replay plays events back in it.
create table if not exists public.client_event (
  event_id    bigint generated by default as identity primary key,
  session_id  uuid not null references public.client_session(session_id) on delete cascade,
  member_id   uuid not null references public.pilot_member(member_id) on delete cascade,
  at          timestamptz not null default now(),
  -- Milliseconds since the visit began. The replay scrubber runs off this, so
  -- playback keeps the real rhythm: the long pause on a look is the point.
  ms_offset   int not null default 0,
  seq         int not null default 0,
  type        text not null check (type in (
                'session_start','page_view','room_open','click','look_open',
                'look_view','item_open','click_out','scroll','search','chat_send',
                'save','upload','verdict','idle','resume','session_end')),
  -- RoomNav ids: for_you, all_looks, dressing_room, inspiration, magazine,
  -- threads, profile.
  room        text,
  path        text,
  label       text,
  target_kind text,
  target_id   text,
  -- Per-type extras: scroll depth, search query, click point, outbound host.
  meta        jsonb not null default '{}'::jsonb
);
create index if not exists idx_client_event_session on public.client_event (session_id, seq);
create index if not exists idx_client_event_member on public.client_event (member_id, at desc);
create index if not exists idx_client_event_type on public.client_event (type, at desc);
alter table public.client_event enable row level security;

-- rrweb emits a snapshot then a stream of mutations. Chunked because a visit is
-- appended to while it is still happening, and rewriting a multi-megabyte jsonb
-- every ten seconds would be the most expensive thing the pilot does. The
-- tracker caps the chunks per visit, so one long session cannot fill the table.
create table if not exists public.client_recording_chunk (
  chunk_id    bigint generated by default as identity primary key,
  session_id  uuid not null references public.client_session(session_id) on delete cascade,
  member_id   uuid not null references public.pilot_member(member_id) on delete cascade,
  chunk_index int not null,
  events      jsonb not null,
  created_at  timestamptz not null default now(),
  unique (session_id, chunk_index)
);
create index if not exists idx_client_recording_session on public.client_recording_chunk (session_id, chunk_index);
alter table public.client_recording_chunk enable row level security;
